#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Polymarket Bitcoin Price History Exporter

set -e

echo "========================================"
echo "Polymarket Exporter - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# SETUP PROJECT
# ============================================

echo -e "${YELLOW}Setting up project structure...${NC}"

# Navigate to polymarket directory
cd polymarket 2>/dev/null || {
    echo -e "${RED}polymarket/ directory not found${NC}"
    echo "Creating polymarket directory..."
    mkdir -p polymarket
    cd polymarket
}

# Check if .csproj exists
if [ ! -f "PolymarketHistoryExporter.csproj" ]; then
    echo -e "${YELLOW}Project file not found. Please run implementation first.${NC}"
    echo "This script is for running an already implemented service."
    exit 1
fi

# ============================================
# RESTORE DEPENDENCIES
# ============================================

echo ""
echo -e "${YELLOW}Restoring NuGet packages...${NC}"
dotnet restore

if [ $? -ne 0 ]; then
    echo -e "${RED}Failed to restore packages${NC}"
    exit 1
fi

echo -e "${GREEN}Packages restored successfully${NC}"

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo -e "${YELLOW}Building project...${NC}"
dotnet build

if [ $? -ne 0 ]; then
    echo -e "${RED}Build failed${NC}"
    exit 1
fi

echo -e "${GREEN}Build succeeded${NC}"

# ============================================
# CREATE OUTPUT DIRECTORIES
# ============================================

echo ""
echo -e "${YELLOW}Creating output directories...${NC}"
mkdir -p output
mkdir -p cache

echo -e "${GREEN}Directories created${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "To run the exporter:"
echo "  cd polymarket && dotnet run"
echo ""
echo "Configuration:"
echo "  Edit appsettings.json to customize API settings"
echo ""
echo "Output:"
echo "  CSV files: ./output/"
echo "  Cache: ./cache/processed_markets.txt"
echo ""
